# Generated by Django 4.1 on 2023-06-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('arq', models.ImageField(default='', upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
