# Generated by Django 4.1 on 2023-06-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0002_produto_delete_myfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='arq',
            new_name='imagem',
        ),
    ]
