# Generated by Django 4.1 on 2023-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='nome',
        ),
    ]
