# Generated by Django 4.1 on 2023-06-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0005_rename_name_contact_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nome',
            field=models.TextField(max_length=50),
        ),
    ]
