# Generated by Django 4.1 on 2023-06-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacto',
        ),
    ]
