# Generated by Django 4.1 on 2023-06-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0008_rename_contact_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nome',
            field=models.TextField(),
        ),
    ]
