# Generated by Django 4.1 on 2023-06-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0009_alter_contacto_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
