# Generated by Django 4.2 on 2023-06-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0011_alter_newsletter_new_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='new_email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
