# Generated by Django 4.2 on 2023-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0013_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='subject',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='mew_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
