# Generated by Django 4.2 on 2023-06-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensac', '0014_remove_newsletter_email_remove_newsletter_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='mew_email',
            new_name='new_email',
        ),
    ]
